---
- name: STORAGE | Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: STORAGE | Initialized MINIO project directory.
  block:
    - name: STORAGE | Check MinIO initial directory
      ansible.builtin.stat:
        path: "{{ minio_docker_project_location }}"
      register: minio_init_dir

    - name: STORAGE | Create minio project directory
      ansible.builtin.file:
        path: "{{ minio_docker_project_location }}"
        state: directory
        mode: "0755"
        recurse: true
      when: not minio_init_dir.stat.exists

  rescue:
    - name: STORAGE | Initialized MINIO project errors
      ansible.builtin.debug:
        msg: "I caught an error, can do stuff here to fix it, :-)"

- name: STORAGE | Setup MINIO project.
  block:
    - name: STORAGE | Check MinIO initial directory
      ansible.builtin.stat:
        path: "{{ minio_docker_project_location }}"
      register: minio_dir

    - name: STORAGE | Create minio persistent data directory.
      ansible.builtin.file:
        path: "{{ minio_docker_project_location }}/data"
        state: directory
        mode: "0755"
        recurse: true
      when:
        - minio_dir.stat.exists
        - minio_dir.stat.isdir

    - name: STORAGE | Copy MinIO docker compose variables
      ansible.builtin.template:
        src: compose.j2
        dest: "{{ minio_docker_project_location }}/docker-compose.yml"
        mode: "0644"
        lstrip_blocks: true
        force: true
      register: copy_compose
      when:
        - minio_dir.stat.exists
        - minio_dir.stat.isdir

    - name: STORAGE | Get infos on container
      community.docker.docker_container_info:
        name: "{{ minio_docker_service_name }}"
      register: minio_container

    - name: STORAGE | Check docker compose file
      ansible.builtin.stat:
        path: "{{ minio_docker_project_location }}/docker-compose.yml"
      register: compose_file

    - name: STORAGE | Stop `docker-compose down` MinIO
      community.docker.docker_compose:
        project_src: "{{ minio_docker_project_location }}"
        state: absent
        remove_orphans: true
      become: true
      register: continer_stop
      when:
        - minio_container.exists
        - copy_compose.changed
    
    - name: Run `docker compose up` again
      community.docker.docker_compose_v2:
        project_src: "{{ minio_docker_project_location }}"
        build: always
      register: output
      when: (not minio_container.exists and minio_dir.stat.isdir and compose_file.stat.exists) or continer_stop.changed


    # - name: STORAGE | Run `docker-compose up` MinIO
    #   community.docker.docker_compose:
    #     project_src: "{{ minio_docker_project_location }}"
    #     build: true
    #   when: (not minio_container.exists and minio_dir.stat.isdir and compose_file.stat.exists) or continer_stop.changed

  #   - name: Creates an entry like "@reboot docker compose minio"
  #     ansible.builtin.cron:
  #       name: "a job for reboot"
  #       special_time: reboot
  #       job: "/usr/local/bin/docker compose -f /home/minio/docker-compose.yml up -d"
  #     when:
  #       - compose_file.stat.exists

  # rescue:
  #   - name: STORAGE | Setup MINIO project errors
  #     ansible.builtin.debug:
  #       msg: "I caught an error, can do stuff here to fix it, :-)"
